### ISSUE TITLE
Difference between ReactorKit and RxFeedback

### ISSUE THREAD

**Issue by eliekarouz** [NoTests/RxFeedback.swift#19]
Hi,
It's more an explanation than an issue. I am new to these architecture and have recently started Rx programming.
1- What's the difference between RxFeedback and ReactorKit ? They look similar but the implementation is a bit different.
2- I would like to implement the business logic in C++. Is there an example on how to do this?
3- When you implement a UI Feedback loop, will the State usually look like the ViewModel?

Thanks,
Elie

**Comment by kzaher** [comment]
Hi @eliekarouz ,

> 1- What's the difference between RxFeedback and ReactorKit ? They look similar but the implementation is a bit different.

I guess the main difference is the number of parts they contain. I can't provide explanation why ReactorKit has the parts it does. You would need to contact @devxoul if you are interested in explanations why some parts are the way they are. I can only answer questions that are specific for this library.

> 2- I would like to implement the business logic in C++. Is there an example on how to do this?

Reducer and State are pure Swift code. They can be written in any other language that is interoperable with Swift.

> 3- When you implement a UI Feedback loop, will the State usually look like the ViewModel?

I would say yes, kind of.

**Comment by eliekarouz** [comment]
Hi @kzaher,
I am currently trying it in a sample project and I would like to know if there is any pattern you are following to share state between different view controllers. Let me explain the problem:
- The app is currently showing VC1(ViewController1). When the user taps on a button the app alternates the current state and as a reaction to this event we will present/push a new VC2. 
Can VC2 start with the state taken from VC1?
Lets assume that in VC2, some events alternated the state. What pattern do you usually use to send back the events/new state to VC1 once VC2 has been dismissed/popped? Do you usually do that?

- Assume a viewController is showing two children viewControllers. How do you manage the communication between the two childrenViewControllers and the communication between the child and its parent. Do you perform the subscription on the parentViewController only or on every childViewController?

- Do you have a plan to share a sample project that might contain some complex workflows (using different screens, database, animations)?

**Comment by disquad** [comment]
@eliekarouz Hello, did you find/made any examples about your questions?

**Comment by eliekarouz** [comment]
@disquad I am actually using RxFeedback. Didn't have the chance to try ReactorKit though.

**Comment by disquad** [comment]
@eliekarouz Yeh, I'm talking about RxFeedback. Can you share any examples for navigation/triggers/etc, I would be very grateful 🙂

**Comment by eliekarouz** [comment]
@eliekarouz I am currently applying RxFeedback at a screen level... So I encode a variable in the state called `route`. It's an `enum Route` and I have a `react` feedback that triggers the navigation (it could be in a `bind` too.

The way I see it (It's still an idea and don't have a proof it works)
I was thinking of actually inverting things but didn't have time to do it or even try it... The idea is to have the state machine control the flow (navigation) so a view controller never starts a system but a `system` places the view controllers on the screen. A state machine would start another inner state machine and so on. Each state machine can show/push multiple view controllers and can update the result to the parent state machine. The ui state will be stored in the state instead of a hidden state in the `UINavigationController`... 
Again this is still an idea if you would like or have time to try it.
