### ISSUE TITLE
Empty events for `Bindings` leads to paired subscriptions get disposed of prematurely

### ISSUE THREAD

**Issue by secretworry** [NoTests/RxFeedback.swift#31]
Some Feedbacks just have subscriptions and using an `Observable#using` to track subscriptions leads to subscriptions' lifecycle depending on the events' lifecycle.
So when passed in an empty `events`, the subscriptions get disposed of instantly.

There are two solutions:
1. Use a `CompositeDisposable` to track their lifecycle separately
2. Concat the events Observable with an `Observable.never()` to ensure it will not get disposed of prematurely

I would like to provide a Pull-request to fix this if we can reach an agreement on which solution to use.

**Comment by kzaher** [comment]
Hi @secretworry ,

I think that we might have resolved that but haven't cut a new release yet.

https://github.com/NoTests/RxFeedback.swift/pull/28/files

Could you try the master branch?

**Comment by secretworry** [comment]
@kzaher Cool! That solved my problem.
Sorry for not testing the master before submitting the issue.
