### ISSUE TITLE
Eventless bindings dispose of subscriptions too early.

### ISSUE THREAD

**Issue by eimantas** [NoTests/RxFeedback.swift#32]
I had a bug where I needed to `bind` and return `Bindings` without any events. The delayed stream was disposed before having a chance to actually send any events.

Consider this piece of code:

```Swift
typealias MyFeedback = Driver<MyState> -> Signal<MyEvent>

func viewDidLoad() {
  super.viewDidLoad()

  let bindings: MyFeedback = bind(self) { owner, state 

    // this driver will send an event when view appears
    // but "view did appear" will never be printed
    let sub = owner.rx.viewDidAppear.do(onNext: { print("view did appear") }).drive()

    let events: [Signal<MyEvent>] = [] // this is needed to disambiguate `Bindings` initialiser
    return Bindings(subscriptions: [sub], events: events)
  }
  Driver.system(initial: MyState.initial, reduce: MyState.reduce, feedback: [bindings])
}
```

The `owner.rx.viewDidAppear` is a stream that sends value whenever VC's view appears. But as stated - the expected console output is never produced. 

I did find the remedy to use `[Signal.never()]` as a value to `events` argument. Maybe a convenience initialiser that accepts only subscriptions would be nice to have? Something like

```Swift
extension Bindings {
  init(subscriptions: [Disposable]) {
    self.init(subscriptions: subscriptions, events: [Signal.never()])
  }
}
```

**Comment by kzaher** [comment]
Hi @eimantas ,

This release should fix your issue https://github.com/NoTests/RxFeedback.swift/releases/tag/1.0.3
