### ISSUE TITLE
Feedback loop type issue

### ISSUE THREAD

**Issue by SylvanasX** [NoTests/RxFeedback.swift#40]
![image](https://user-images.githubusercontent.com/8180975/46268493-4f756180-c56d-11e8-876f-8dbff0fe97ff.png)
![image 1](https://user-images.githubusercontent.com/8180975/46268502-58fec980-c56d-11e8-9f98-b2cbcc5908e2.png)

RxFeedback when use `bindUI: (ObservableSchedulerContext<State>) -> Observable<Mutation>`? when use `bindUI: (Driver<State>) -> Signal<Mutation>`, the bindUI has different type, what different between them?

Which bindUI type should use in different case?

**Comment by eliekarouz** [comment]
Hi @SylvanasX, I have answered you on Slack.
