### ISSUE TITLE
Can't build version 1.1.0 with Carthage

### ISSUE THREAD

**Issue by ferranpujolcamins** [NoTests/RxFeedback.swift#41]
When I do 'carthage build --no-skip-current' I get the following error:

`Failed to write to /Users/ferranpujolcamins/development/RxFeedback.swift/Carthage/Build/Mac/RxFeedback.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “RxFeedback.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/ferranpujolcamins/Library/Developer/Xcode/DerivedData/RxFeedback-hlgvungruiurhlczuflxvahyfwrv/Build/Intermediates.noindex/ArchiveIntermediates/RxFeedback/BuildProductsPath/Release-iphoneos/RxFeedback.framework, NSFilePath=/Users/ferranpujolcamins/Library/Developer/Xcode/DerivedData/RxFeedback-hlgvungruiurhlczuflxvahyfwrv/Build/Intermediates.noindex/ArchiveIntermediates/RxFeedback/BuildProductsPath/Release-iphoneos/RxFeedback.framework, NSUnderlyingError=0x7fc514926810 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

**Comment by kzaher** [comment]
This should be fixed in 1.1.1
