### ISSUE TITLE
RequestLifetimeTracking forwardRequests:  Duplicate keys were found in Dictionary

### ISSUE THREAD

**Issue by leandromperez** [NoTests/RxFeedback.swift#52]
Hi, 
First of all, thanks again for both RxSwift and RxFeedback, I really appreciate your work!

I'm not sure if this is the right channel for presenting this issue, but I'm experiencing (quite randomly but frequently) a crash for which I'm running out of ideas:

Thread 1: Fatal error: Duplicate keys of type 'ClassesStateMachine' were found in a Dictionary.

This is part of the stack trace:
#0	0x00000001f9231194 in _swift_runtime_on_report ()
#1	0x00000001f928781c in _swift_stdlib_reportFatalError ()
#2	0x00000001f8fd0ff4 in specialized String._withUnsafeBufferPointerToUTF8<A>(_:) ()
#3	0x00000001f91b4de0 in specialized _assertionFailure(_ : _ : flags:) ()
#4	0x00000001f90ca048 in KEY_TYPE_OF_DICTIONARY_VIOLATES_HASHABLE_REQUIREMENTS(_:) ()
#5	0x00000001f9035084 in _NativeDictionary.setValue(_:forKey:isUnique:) ()
#6	0x00000001f9015268 in Dictionary._Variant.setValue(_:forKey:) ()
#7	0x00000001f91d7b20 in specialized Dictionary.subscript.setter ()
#8	0x00000001f8fe32d8 in Dictionary.subscript.setter ()
#9	0x0000000104a7b760 in closure #1 in **RequestLifetimeTracking.forwardRequests**(_:) at myProject/Pods/RxFeedback/Sources/RxFeedback/Feedbacks.swift:**160**
#10	0x0000000104a77cfc in **AsyncSynchronized.async**(_:) at myProject/Pods/RxFeedback/Sources/RxFeedback/AsyncSynchronized.swift:32
#11	0x0000000104a7ad38 in RequestLifetimeTracking.forwardRequests(_:) at myProject/Pods/RxFeedback/Sources/RxFeedback/Feedbacks.swift:148
#12	0x0000000104a7dd90 in closure #1 in closure #1 in closure #1 in react<A, B, C, D>(requests:effects:) at myProject/Pods/RxFeedback/Sources/RxFeedback/Feedbacks.swift:236

The line that crashes is 160:
  state.lifetimeByIdentifier[requestID] = (...)

Could it be possible that this method:

```
internal func async(_ mutate: @escaping Mutate) {
        guard var executeMutation = self.enqueue(mutate) else {
            return
        }
        repeat {
            executeMutation(&state) // -> is a lock needed here?
            guard let nextExecute = self.dequeue() else {
                return
            }
            executeMutation = nextExecute
        } while true
    }
```
mutates concurrently the state, therefore the dictionary, creating duplicate entries?

I'm wondering if that code needs to be synchronized too like queue and enqueue in the same class.

Any thoughts?

Not sure if this information helps, but: ClassesStateMachine is a Request object that I'm returning as part of some of the feedbacks that I have registered in a Driver.system. I'm using a Set to keep alive some of the requests and services started in previous loops. 

I'd really appreciate any ideas you might have about this,
Thanks again!
Leandro

**Comment by eliekarouz** [comment]
@leandromperez,
It would be nice if you can isolate your code and post it here. 

> Could it be possible that this method: ... mutates concurrently the state, therefore the dictionary, creating duplicate entries?

No, this method executes blocks in a serial fashion.

**Comment by leandromperez** [comment]
Hi @eliekarouz,
Thanks for your answer. 
This is a really condensed version of the code, there are many different parts to it, but this is mostly what's related to the feedback loop:

```

struct ClassesStateMachine{
   //This is the State
         ...    
}

extension ClassesStateMachine {
    typealias FeedbackLoop = (Driver<ClassesStateMachine>) -> Signal<ClassesStateMachine.Event>

    struct Feedback {

	//This is the system driver, a reduced version of it
        static func statemachineFeedbackDriver(_ interactor: ClassesInteractorImp) -> Driver<ClassesStateMachine> {
		
		return Driver.system(initialState: ClassesStateMachine.initialState,
				     reduce: ClassesStateMachine.reduce,
				     feedback:
						Feedback.uiFeedback(interactor),
						Feedback.processInteractions(interactor))
        }


        //This is the feedback that will analyze the state and respond with a service execution. E.g. when the user interacts with the screen, like tapping a button to execute some logic in the backend.
	//It returns a Set of Statemachine to avoid cancelling pending services of previous loops (i.e. interactios generated in previous Statemachines)
        private static func processInteractions(_ interactor: ClassesInteractorImp) -> ClassesStateMachine.FeedbackLoop {

            let interactionToProcess : (ClassesStateMachine) -> Set<ClassesStateMachine> = { statemachine in
                if statemachine.interactionToProcess != nil {
                    return Set([statemachine])
                }
                return Set()
            }

            let processInteraction : (ClassesStateMachine) -> Signal<ClassesStateMachine.Event> = { (statemachine) in
                return interactor.executeInteraction(of:statemachine)
            }

            return react(requests: interactionToProcess, effects: processInteraction)
        }

	//This binds te UI with the state
        private static func uiFeedback(_ interactor : ClassesInteractorImp) -> ClassesStateMachine.FeedbackLoop {

            return bind {[unowned interactor] stateMachine in

                let subscriptions = [
                    stateMachine.drive(interactor.presenter.statemachineInput),
                ]

                let events : [Signal<ClassesStateMachine.Event>] = [ interactor.viewController.userEvents]

                return Bindings(subscriptions: subscriptions, events: events)
            }
        }
    }
}

extension ClassesInteractorImp {

    //An interaction is an action that the user can perform on the screen, containing the necessary data to execute a service
    func executeInteraction( of statemachine:ClassesStateMachine) -> Signal<ClassesStateMachine.Event> {

        guard let interaction = statemachine.interactionToProcess else {fatalError("The statemachine must have an interaction")}

        let service = self.service(for:interaction, of: statemachine)

        return service.asSignal(onErrorRecover: { .just( ClassesStateMachine.Event.didFail(interaction, error:$0)) })
    }

    //This will perform a service, i.e. talk to the backend, and create an event when the response is obtained.
    func service(for interaction: ClassesStateMachine.Interaction, of statemachine: ClassesStateMachine) -> Observable<ClassesStateMachine.Event>{

        switch interaction {

        case .doSomething :
            return doSomething(with: statemachine) // talks to the backend to doSomething and returns an Event in response

            ...
        }
}
``` 

I was thinking that maybe more than one effect was mutating that dictionary concurrently, because I cannot think of another way of inserting a second object with an existing key into that dictionary.
 
We're not calling this function directly: `public func react<State, Request: Equatable, RequestID, Event>(
    requests: @escaping (State) -> [RequestID: Request],
    effects: @escaping (_ initial: Request, _ state: Observable<Request>)`

We're calling this one: `public func react<State, Request, Event>(
    requests: @escaping (State) -> Set<Request>,
    effects: @escaping (Request) -> Signal<Event>
)`

I hope this information is useful somehow,
Thanks again,
Leandro

**Comment by eliekarouz** [comment]
@leandromperez How are you declaring hashable/equatable for the `ClassesStateMachine`. Could it be that you have by mistake reference types that are being mutated AND used to compute the hash or `==`

**Comment by leandromperez** [comment]
```
struct ClassesStateMachine {
    var id : Int
}

extension ClassesStateMachine: Equatable {}
func == (lhs: ClassesStateMachine, rhs: ClassesStateMachine) -> Bool {
    return lhs.id == rhs.id
}
```
Sometimes the reducer returns a StateMachine that doesn't mutate the id, to avoid repeating some effects in the next loop. I don't see how that could cause that crash, but do you think it might be a problem?

**Comment by eliekarouz** [comment]
@leandromperez ,
Please check this line:
https://github.com/apple/swift/blob/f978cb0ba32acad5cc434331fa6a6b0c39ea9358/stdlib/public/core/NativeDictionary.swift#L449

Try to look in your code for classes (reference types) not enums or structs (value types)... Most probably you are mutating the variables inside these classes which is causing this crash.

FYI this code crashes with a similar error because the class `XString` is being mutated...

```swift
class XString: Hashable, Equatable {
    static func == (lhs: XString, rhs: XString) -> Bool {
        return lhs.string == rhs.string
    }

    var string: String

    init(_ string: String) {
        self.string = string
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine(string)
    }
}

struct FakeValueType: Hashable, Equatable {
    let xstring: XString
}

func test() {
    let str1 = FakeValueType(xstring: XString("SomeString"))
    var dict = [str1: 0]
    for i in 0...100 {
        str1.xstring.string = "Mutation\(i) for SomeString"
        dict[str1] = i
    }
}

```

**Comment by leandromperez** [comment]
@eliekarouz That makes sense. 

If I understood correctly, the problem comes when the struct (that's used as the dictionary key) is associated with a reference type instance, and when such instance is used to calculate the hash value. 

I couldn't find a reference type instance inside the graph of associations that are used inside the hash function. But anyways, there might be one hidden somewhere I've missed. 

So, I've changed the hashing code so it depends only on the identifier that's used inside the equals function. Hopefully, that will fix the issue.

I can close this ticket and re-open it if necessary,

Thanks for your help!
