### ISSUE TITLE
bind(self) { ... } leaks

### ISSUE THREAD

**Issue by anton-plebanovich** [NoTests/RxFeedback.swift#58]
`bind` variant that takes `_ owner: WeakOwner` actually just captures an owner strongly because it is executed on `Observer.system` creation and returns closure with a captured object. I'm using `bind` without `owner` and doing strongify manually as a workaround for now.

**Comment by chriskilpin** [comment]
Hi There I am having a similar issue. Just wondering how you are "doing strongify manually as a workaround for now" ?

**Comment by anton-plebanovich** [comment]
@chriskilpin Somehow like that:
```swift
Observable
    .system(initialState: ...,
            reduce: ...,
            scheduler: CurrentThreadScheduler.instance,
            feedback: bind { [weak self] state in
                guard let _self = self else { return Bindings(subscriptions: [], events: [Observable<MyEvent>]()) }
                
                let subscriptions = ...
                let events = ...
                
                return Bindings(subscriptions: subscriptions, events: events)
    })
    .subscribe()
    .disposed(by: disposeBag)
```

**Comment by beeth0ven** [comment]
Hi There.

Thanks for reporting the issue. 

As for as I known, the imapletation of `bind(self) { ... }` is: 

```swift
public func bind<State, Event, WeakOwner>(
  _ owner: WeakOwner, 
  _ bindings: @escaping (WeakOwner, Driver<State>) -> (Bindings<Event>)
) -> (Driver<State>) -> Signal<Event> where WeakOwner: AnyObject {
    return bind { [weak owner] state -> Bindings<Event> in
        guard let strongOwner = owner else {
            return Bindings(subscriptions: [], events: [Observable<Event>]())
        }
        return bindings(strongOwner, state)
    }
}
```

The `[weak owner]` will not capture `owner` theoretically.

Can you provide a minimal code to reproduce the issues.

I'm ready to investgate.  🙂

**Comment by anton-plebanovich** [comment]
@beeth0ven It looks like I just misused `bind` and captured a method of `self` within it so that was an issue. Closing this one.
