### ISSUE TITLE
Carthage for macOS

### ISSUE THREAD

**Issue by fabianmuecke** [NoTests/RxFeedback.swift#60]
I'm trying to add RxFeedback to my macOS App using Carthage and getting a build error when running `carthage update RxFeedback --platform Mac`

```
error: Building for macOS, but the linked framework 'RxCocoa.framework' was built for iOS + iOS Simulator. (in target 'RxFeedback' from project 'RxFeedback')
error: Building for macOS, but the linked framework 'RxSwift.framework' was built for iOS + iOS Simulator. (in target 'RxFeedback' from project 'RxFeedback')
```

Could you give me a hint as to what I'm doing wrong or have a look to see if this is a bug?

**Comment by kzaher** [comment]
Probably a bug with Carthage and include paths.
