### ISSUE TITLE
New Release Tag

### ISSUE THREAD

**Issue by mRs-** [NoTests/RxFeedback.swift#62]
Is it possible to get a new release tag with the changes from @fabianmuecke ?

**Comment by freak4pc** [comment]
I would be happy to help but I believe only Kruno has access to do this for this project :(

**Comment by mRs-** [comment]
@freak4pc could you provide one 🤩 ?

**Comment by kzaher** [comment]
I've added Shai to be the owner of RxFeedback.podspec 

https://cocoapods.org/pods/RxFeedback

**Comment by mRs-** [comment]
Can we get a new release 🥺

**Comment by mRs-** [comment]
and we can use this as an option to bump RxSwift 6.0 as well

**Comment by mRs-** [comment]
We could even name it 4.0.0 😄

**Comment by freak4pc** [comment]
It only took 8 months ;-) sorry! 

 🎉  Congrats

 🚀  RxFeedback (4.0.0) successfully published
 📅  January 14th, 07:58
 🌎  https://cocoapods.org/pods/RxFeedback
 👍  Tell your friends!

**Comment by mRs-** [comment]
Thanks 😀
